//! 0.1.4 — the presentation preferences out of `state.toml`, and the agents
//! nobody installed out of `settings.toml`.
//!
//! Deleted with `model::migrate::v0_1_4` when that is retired.

use cydonia_gui::model::migrate::v0_1_4::{carry_appearance, drop_default_agents};
use toml_edit::DocumentMut;

fn doc(body: &str) -> DocumentMut {
    body.parse().expect("valid toml")
}

/// A state file as it was written before the move.
fn legacy() -> DocumentMut {
    doc(r#"
projects = ["/Users/someone/work"]
active = 0
appearance = "dark"
opaque = true
cursor_blink = false
text_size = 15.0
hue = 240.0
chroma = 0.02
wide_pages = true

[last."/Users/someone/work"]
kind = "article"
id = "1757000000000"
"#)
}

#[test]
fn every_preference_lands_in_the_settings_table() {
    let (mut state, mut settings) = (legacy(), doc(""));
    assert!(carry_appearance(&mut state, &mut settings));

    let held = settings["appearance"].as_table().expect("a table");
    // `appearance` was a bare key naming the mode; the table took that name,
    // so the value inside it is `mode`.
    assert_eq!(held["mode"].as_str(), Some("dark"));
    assert_eq!(held["opaque"].as_bool(), Some(true));
    assert_eq!(held["cursor_blink"].as_bool(), Some(false));
    assert_eq!(held["text_size"].as_float(), Some(15.0));
    assert_eq!(held["hue"].as_float(), Some(240.0));
    assert_eq!(held["chroma"].as_float(), Some(0.02));
    assert_eq!(held["wide_pages"].as_bool(), Some(true));
}

/// What is left is bookkeeping, which is the whole point of the move.
#[test]
fn the_state_file_keeps_only_what_the_machine_wrote() {
    let (mut state, mut settings) = (legacy(), doc(""));
    carry_appearance(&mut state, &mut settings);

    let left: Vec<&str> = state.iter().map(|(key, _)| key).collect();
    assert_eq!(left, vec!["projects", "active", "last"]);
    assert!(state.to_string().contains("/Users/someone/work"));
}

/// It runs on every launch, so a second one must be a no-op rather than a
/// second write.
#[test]
fn a_file_already_moved_is_left_alone() {
    let (mut state, mut settings) = (legacy(), doc(""));
    assert!(carry_appearance(&mut state, &mut settings));
    assert!(
        !carry_appearance(&mut state, &mut settings),
        "nothing left to carry"
    );
}

/// The settings file is the one a person edits. A stale copy left behind in
/// `state.toml` must never overwrite what they wrote there.
#[test]
fn what_is_already_in_settings_wins() {
    let mut state = legacy();
    let mut settings = doc(r#"
[appearance]
mode = "light"
"#);
    carry_appearance(&mut state, &mut settings);

    let held = settings["appearance"].as_table().expect("a table");
    assert_eq!(held["mode"].as_str(), Some("light"), "the hand-written one");
    // The rest still comes across: only the key that was already answered
    // stands.
    assert_eq!(held["text_size"].as_float(), Some(15.0));
}

/// Comments are why `settings.toml` is edited rather than re-serialised.
#[test]
fn a_hand_written_comment_survives_the_move() {
    let mut state = legacy();
    let mut settings = doc(r#"# generated by cydonia — edits are kept
cover_memory = 256

[mcp]
# I turned this off on purpose
serve = false
"#);
    carry_appearance(&mut state, &mut settings);

    let written = settings.to_string();
    assert!(written.contains("# generated by cydonia"));
    assert!(written.contains("# I turned this off on purpose"));
    assert!(written.contains("serve = false"));
}

/// A fresh install has none of these keys, and must not be given an empty
/// table saying so.
#[test]
fn a_state_file_with_nothing_to_move_is_untouched() {
    let mut state = doc("projects = []\nactive = 0\n");
    let mut settings = doc("cover_memory = 256\n");
    assert!(!carry_appearance(&mut state, &mut settings));
    assert!(settings.get("appearance").is_none());
}

/// The key that never shipped in a release, carried anyway: a build off `dev`
/// wrote it, and those are the files most likely to be sitting on disk here.
#[test]
fn wrap_code_comes_across_too() {
    let mut state = doc("wrap_code = true\n");
    let mut settings = doc("");
    assert!(carry_appearance(&mut state, &mut settings));
    assert_eq!(settings["appearance"]["wrap_code"].as_bool(), Some(true));
}

// ── the agents nobody installed ──────────────────────────────────

/// A settings file as 0.1.3 wrote one: the two `npx` lines at the end of it.
fn shipped() -> DocumentMut {
    doc(
        r#"# generated by cydonia — edits are kept, deleting regenerates defaults

cover_memory = 256

[features]
sessions = true

[[agents]]
name = "claude"
command = "npx"
args = ["-y", "@agentclientprotocol/claude-agent-acp@0.73.0"]

[[agents]]
name = "codex"
command = "npx"
args = ["-y", "@agentclientprotocol/codex-acp@1.8.0"]
"#,
    )
}

#[test]
fn the_two_lines_nobody_installed_go() {
    let mut settings = shipped();
    assert!(drop_default_agents(&mut settings));

    let agents = settings["agents"].as_array_of_tables().expect("the list");
    assert!(agents.is_empty(), "both were cydonia's own");
    let written = settings.to_string();
    assert!(!written.contains("claude-agent-acp"));
    assert!(!written.contains("codex-acp"));
    // Everything the file is actually for is untouched.
    assert!(written.contains("# generated by cydonia"));
    assert!(written.contains("cover_memory = 256"));
    assert!(written.contains("sessions = true"));
}

/// It runs on every launch, so a second one must find nothing.
#[test]
fn a_file_already_cleared_is_left_alone() {
    let mut settings = shipped();
    assert!(drop_default_agents(&mut settings));
    assert!(!drop_default_agents(&mut settings), "nothing left to drop");
}

/// An install writes the registry id onto the entry, and that is the mark of a
/// line something stands behind.
#[test]
fn an_installed_agent_stays() {
    let mut settings = doc(r#"
[[agents]]
name = "claude"
id = "claude-acp"
command = "npx"
args = ["-y", "@agentclientprotocol/claude-agent-acp@0.73.0"]
"#);
    assert!(!drop_default_agents(&mut settings));
}

/// An `npx` line does work. One somebody shaped themselves — renamed, or given
/// an environment — is theirs, whatever package it names.
#[test]
fn a_hand_written_line_stays() {
    let mut settings = doc(r#"
[[agents]]
name = "my claude"
command = "npx"
args = ["-y", "@agentclientprotocol/claude-agent-acp@0.73.0"]

[[agents]]
name = "codex"
command = "npx"
args = ["-y", "@agentclientprotocol/codex-acp@1.8.0"]
env = { OPENAI_API_KEY = "sk-…" }

[[agents]]
name = "claude"
command = "bunx"
args = ["-y", "@agentclientprotocol/claude-agent-acp@0.73.0"]
"#);
    assert!(!drop_default_agents(&mut settings));
    assert_eq!(
        settings["agents"]
            .as_array_of_tables()
            .expect("the list")
            .len(),
        3
    );
}

/// The header hangs off whichever table comes first. Dropping that one must
/// not take a comment somebody wrote with it.
#[test]
fn a_comment_above_the_first_entry_moves_down() {
    let mut settings = doc(r#"
# the agents I can run
[[agents]]
name = "claude"
command = "npx"
args = ["-y", "@agentclientprotocol/claude-agent-acp@0.73.0"]

[[agents]]
name = "gemini"
id = "gemini"
command = "/Users/someone/.local/share/cydonia/gemini/bin/gemini"
args = ["--experimental-acp"]
"#);
    assert!(drop_default_agents(&mut settings));

    let written = settings.to_string();
    assert!(written.contains("# the agents I can run"));
    assert!(written.contains("gemini"));
    assert!(!written.contains("claude"));
}

/// A file with no `[[agents]]` at all, which is what a fresh install writes now.
#[test]
fn a_file_naming_no_agent_is_untouched() {
    let mut settings = doc("cover_memory = 256\n");
    assert!(!drop_default_agents(&mut settings));
}
