[package]
name = "cydonia"
description = "Desktop client for ACP agents"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"

[[bin]]
name = "cydonia"
path = "bin/main.rs"

[dependencies]
anyhow.workspace = true
bezel.workspace = true
cacp.workspace = true
cacp-agents.workspace = true
dirs.workspace = true
editor.workspace = true
markdown.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
syntax.workspace = true
tokio.workspace = true
toml.workspace = true
toml_edit.workspace = true
ui.workspace = true
ureq.workspace = true
