//! Auto-generated settings — written with defaults on first run, read on
//! launch. Editable, but never requires user maintenance.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::{collections::BTreeMap, path::PathBuf};

#[derive(Debug, Serialize, Deserialize)]
pub struct Settings {
    #[serde(default)]
    pub agents: Vec<Agent>,
}

/// One launchable ACP agent: `command args...` spawned over stdio.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Agent {
    pub name: String,
    pub command: String,
    #[serde(default)]
    pub args: Vec<String>,
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub env: BTreeMap<String, String>,
    /// MCP servers handed to the agent at `session/new` (stdio transport).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub mcp_servers: Vec<McpServer>,
}

/// One MCP server offered to agents: either a local `command args...`
/// over stdio, or a remote `url` (which needs the agent to support HTTP
/// MCP).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct McpServer {
    pub name: String,
    #[serde(default = "enabled_by_default")]
    pub enabled: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub args: Vec<String>,
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub env: BTreeMap<String, String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The MCP registry id this came from, when it came from there.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

const fn enabled_by_default() -> bool {
    true
}

impl Default for Settings {
    fn default() -> Self {
        let npx = |name: &str, pkg: &str| Agent {
            name: name.into(),
            command: "npx".into(),
            args: vec!["-y".into(), pkg.into()],
            env: BTreeMap::new(),
            mcp_servers: Vec::new(),
        };
        Self {
            agents: vec![
                npx("claude", "@agentclientprotocol/claude-agent-acp@latest"),
                npx("codex", "@agentclientprotocol/codex-acp@latest"),
            ],
        }
    }
}

/// Cydonia's config directory: `$XDG_CONFIG_HOME/cydonia`, defaulting to
/// `~/.config/cydonia` — on macOS too, so a hand-edited settings.toml sits
/// where its neighbours do rather than in Application Support.
pub fn dir() -> Result<PathBuf> {
    if let Ok(xdg) = std::env::var("XDG_CONFIG_HOME")
        && !xdg.is_empty()
    {
        return Ok(PathBuf::from(xdg).join("cydonia"));
    }
    Ok(dirs::home_dir()
        .context("no home directory on this system")?
        .join(".config")
        .join("cydonia"))
}

// ── MCP server store ─────────────────────────────────────────────

#[derive(Debug, Default, Serialize, Deserialize)]
struct McpStore {
    #[serde(default)]
    servers: Vec<McpServer>,
}

fn mcp_path() -> Option<PathBuf> {
    dir().ok().map(|d| d.join("mcp.toml"))
}

/// Every MCP server the user has added, enabled or not.
pub fn mcp_servers() -> Vec<McpServer> {
    mcp_path()
        .and_then(|p| std::fs::read_to_string(p).ok())
        .and_then(|s| toml::from_str::<McpStore>(&s).ok())
        .map(|store| store.servers)
        .unwrap_or_default()
}

pub fn load() -> Result<Settings> {
    let dir = dir()?;
    let path = dir.join("settings.toml");
    if !path.exists() {
        let settings = Settings::default();
        std::fs::create_dir_all(&dir)?;
        let body = format!(
            "# generated by cydonia — edits are kept, deleting regenerates defaults\n\n{}",
            toml::to_string_pretty(&settings)?
        );
        std::fs::write(&path, body)?;
        return Ok(settings);
    }
    let content = std::fs::read_to_string(&path)?;
    toml::from_str(&content).with_context(|| format!("invalid settings: {}", path.display()))
}
