//! 0.1.4 — moving the presentation preferences out of `state.toml`.
//!
//! Deleted with `model::migrate::v0_1_4` when that is retired.

use cydonia::model::migrate::v0_1_4::carry_appearance;
use toml_edit::DocumentMut;

fn doc(body: &str) -> DocumentMut {
    body.parse().expect("valid toml")
}

/// A state file as it was written before the move.
fn legacy() -> DocumentMut {
    doc(r#"
projects = ["/Users/someone/work"]
active = 0
appearance = "dark"
opaque = true
cursor_blink = false
text_size = 15.0
hue = 240.0
chroma = 0.02
wide_pages = true

[last."/Users/someone/work"]
kind = "article"
id = "1757000000000"
"#)
}

#[test]
fn every_preference_lands_in_the_settings_table() {
    let (mut state, mut settings) = (legacy(), doc(""));
    assert!(carry_appearance(&mut state, &mut settings));

    let held = settings["appearance"].as_table().expect("a table");
    // `appearance` was a bare key naming the mode; the table took that name,
    // so the value inside it is `mode`.
    assert_eq!(held["mode"].as_str(), Some("dark"));
    assert_eq!(held["opaque"].as_bool(), Some(true));
    assert_eq!(held["cursor_blink"].as_bool(), Some(false));
    assert_eq!(held["text_size"].as_float(), Some(15.0));
    assert_eq!(held["hue"].as_float(), Some(240.0));
    assert_eq!(held["chroma"].as_float(), Some(0.02));
    assert_eq!(held["wide_pages"].as_bool(), Some(true));
}

/// What is left is bookkeeping, which is the whole point of the move.
#[test]
fn the_state_file_keeps_only_what_the_machine_wrote() {
    let (mut state, mut settings) = (legacy(), doc(""));
    carry_appearance(&mut state, &mut settings);

    let left: Vec<&str> = state.iter().map(|(key, _)| key).collect();
    assert_eq!(left, vec!["projects", "active", "last"]);
    assert!(state.to_string().contains("/Users/someone/work"));
}

/// It runs on every launch, so a second one must be a no-op rather than a
/// second write.
#[test]
fn a_file_already_moved_is_left_alone() {
    let (mut state, mut settings) = (legacy(), doc(""));
    assert!(carry_appearance(&mut state, &mut settings));
    assert!(
        !carry_appearance(&mut state, &mut settings),
        "nothing left to carry"
    );
}

/// The settings file is the one a person edits. A stale copy left behind in
/// `state.toml` must never overwrite what they wrote there.
#[test]
fn what_is_already_in_settings_wins() {
    let mut state = legacy();
    let mut settings = doc(r#"
[appearance]
mode = "light"
"#);
    carry_appearance(&mut state, &mut settings);

    let held = settings["appearance"].as_table().expect("a table");
    assert_eq!(held["mode"].as_str(), Some("light"), "the hand-written one");
    // The rest still comes across: only the key that was already answered
    // stands.
    assert_eq!(held["text_size"].as_float(), Some(15.0));
}

/// Comments are why `settings.toml` is edited rather than re-serialised.
#[test]
fn a_hand_written_comment_survives_the_move() {
    let mut state = legacy();
    let mut settings = doc(r#"# generated by cydonia — edits are kept
cover_memory = 256

[mcp]
# I turned this off on purpose
serve = false
"#);
    carry_appearance(&mut state, &mut settings);

    let written = settings.to_string();
    assert!(written.contains("# generated by cydonia"));
    assert!(written.contains("# I turned this off on purpose"));
    assert!(written.contains("serve = false"));
}

/// A fresh install has none of these keys, and must not be given an empty
/// table saying so.
#[test]
fn a_state_file_with_nothing_to_move_is_untouched() {
    let mut state = doc("projects = []\nactive = 0\n");
    let mut settings = doc("cover_memory = 256\n");
    assert!(!carry_appearance(&mut state, &mut settings));
    assert!(settings.get("appearance").is_none());
}

/// The key that never shipped in a release, carried anyway: a build off `dev`
/// wrote it, and those are the files most likely to be sitting on disk here.
#[test]
fn wrap_code_comes_across_too() {
    let mut state = doc("wrap_code = true\n");
    let mut settings = doc("");
    assert!(carry_appearance(&mut state, &mut settings));
    assert_eq!(settings["appearance"]["wrap_code"].as_bool(), Some(true));
}
