name = "Material"

[dark.seed]
surface = "#212121"
ink = "#eeffff"
accent = "#80cbc4"
added = "#c3e88d"
removed = "#f07178"
highlight = "#c792ea"

[dark.syntax]
comment = "#616161"
keyword = "#c792ea"
string = "#c3e88d"
string_special = "#89ddff"
escape = "#89ddff"
number = "#f78c6c"
boolean = "#ff9cac"
type_name = "#ffcb6b"
type_builtin = "#ffcb6b"
constructor = "#ffcb6b"
function = "#82aaff"
function_builtin = "#82aaff"
macro_name = "#89ddff"
property = "#f07178"
constant = "#f78c6c"
variable = "#eeffff"
variable_special = "#ff5370"
parameter = "#eeffff"
operator = "#89ddff"
punctuation = "#89ddff"
tag = "#f07178"
attribute = "#c792ea"
label = "#ffcb6b"
invalid = "#ff5370"

[dark.terminal.ansi]
black = "#000000"
red = "#ff5370"
green = "#c3e88d"
yellow = "#ffcb6b"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#89ddff"
white = "#ffffff"
bright_black = "#545454"
bright_red = "#ff5370"
bright_green = "#c3e88d"
bright_yellow = "#ffcb6b"
bright_blue = "#82aaff"
bright_magenta = "#c792ea"
bright_cyan = "#89ddff"
bright_white = "#ffffff"
