name = "Monokai"

[dark.seed]
surface = "#272822"
ink = "#f8f8f2"
accent = "#99947c"
added = "#86b42b"
removed = "#c4265e"
highlight = "#8c6bc8"

[dark.syntax]
comment = "#75715e"
keyword = "#f92672"
string = "#e6db74"
string_special = "#e6db74"
escape = "#ae81ff"
number = "#ae81ff"
boolean = "#ae81ff"
type_name = "#66d9ef"
type_builtin = "#66d9ef"
constructor = "#a6e22e"
function = "#a6e22e"
function_builtin = "#66d9ef"
macro_name = "#f92672"
property = "#f8f8f2"
constant = "#ae81ff"
variable = "#f8f8f2"
variable_special = "#fd971f"
parameter = "#fd971f"
operator = "#f92672"
punctuation = "#f8f8f2"
tag = "#f92672"
attribute = "#a6e22e"
label = "#e6db74"
invalid = "#f92672"

[dark.terminal.ansi]
black = "#272822"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f8f8f2"
bright_black = "#75715e"
bright_red = "#f92672"
bright_green = "#a6e22e"
bright_yellow = "#f4bf75"
bright_blue = "#66d9ef"
bright_magenta = "#ae81ff"
bright_cyan = "#a1efe4"
bright_white = "#f9f8f5"
