name = "Night Owl"

[dark.seed]
surface = "#011627"
ink = "#d6deeb"
accent = "#82aaff"
added = "#c5e478"
removed = "#ef5350"
highlight = "#c792ea"

[dark.syntax]
comment = "#637777"
keyword = "#c792ea"
string = "#ecc48d"
string_special = "#ecc48d"
escape = "#f78c6c"
number = "#f78c6c"
boolean = "#ff5874"
type_name = "#ffcb8b"
type_builtin = "#ffcb8b"
constructor = "#ffcb8b"
function = "#82aaff"
function_builtin = "#82aaff"
macro_name = "#c792ea"
property = "#7fdbca"
constant = "#82aaff"
variable = "#d6deeb"
variable_special = "#addb67"
parameter = "#d7dbe0"
operator = "#c792ea"
punctuation = "#d6deeb"
tag = "#caece6"
attribute = "#c5e478"
label = "#7fdbca"
invalid = "#ef5350"

[dark.terminal.ansi]
black = "#011627"
red = "#ef5350"
green = "#22da6e"
yellow = "#addb67"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#21c7a8"
white = "#ffffff"
bright_black = "#575656"
bright_red = "#ef5350"
bright_green = "#22da6e"
bright_yellow = "#ffeb95"
bright_blue = "#82aaff"
bright_magenta = "#c792ea"
bright_cyan = "#7fdbca"
bright_white = "#ffffff"
