name = "Nord"

[dark.seed]
surface = "#2e3440"
ink = "#d8dee9"
accent = "#88c0d0"
added = "#a3be8c"
removed = "#bf616a"
highlight = "#b48ead"

[dark.syntax]
comment = "#616e88"
keyword = "#81a1c1"
string = "#a3be8c"
string_special = "#ebcb8b"
escape = "#ebcb8b"
number = "#b48ead"
boolean = "#81a1c1"
type_name = "#8fbcbb"
type_builtin = "#81a1c1"
constructor = "#8fbcbb"
function = "#88c0d0"
function_builtin = "#88c0d0"
macro_name = "#5e81ac"
property = "#d8dee9"
constant = "#81a1c1"
variable = "#d8dee9"
variable_special = "#81a1c1"
parameter = "#d8dee9"
operator = "#81a1c1"
punctuation = "#eceff4"
tag = "#81a1c1"
attribute = "#8fbcbb"
label = "#ebcb8b"
invalid = "#bf616a"

[dark.terminal.ansi]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"
bright_black = "#4c566a"
bright_red = "#bf616a"
bright_green = "#a3be8c"
bright_yellow = "#ebcb8b"
bright_blue = "#81a1c1"
bright_magenta = "#b48ead"
bright_cyan = "#8fbcbb"
bright_white = "#eceff4"
