name = "Rosé Pine"

[dark.seed]
surface = "#232136"
ink = "#e0def4"
accent = "#ea9a97"
added = "#9ccfd8"
removed = "#eb6f92"
highlight = "#c4a7e7"

[dark.syntax]
comment = "#6e6a86"
keyword = "#3e8fb0"
string = "#f6c177"
string_special = "#f6c177"
escape = "#3e8fb0"
number = "#f6c177"
boolean = "#ea9a97"
type_name = "#9ccfd8"
type_builtin = "#9ccfd8"
constructor = "#9ccfd8"
function = "#ea9a97"
function_builtin = "#ea9a97"
macro_name = "#c4a7e7"
property = "#9ccfd8"
constant = "#f6c177"
variable = "#e0def4"
variable_special = "#eb6f92"
parameter = "#c4a7e7"
operator = "#908caa"
punctuation = "#908caa"
tag = "#9ccfd8"
attribute = "#c4a7e7"
label = "#9ccfd8"
invalid = "#eb6f92"

[dark.terminal.ansi]
black = "#393552"
red = "#eb6f92"
green = "#3e8fb0"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ea9a97"
white = "#e0def4"
bright_black = "#6e6a86"
bright_red = "#eb6f92"
bright_green = "#3e8fb0"
bright_yellow = "#f6c177"
bright_blue = "#9ccfd8"
bright_magenta = "#c4a7e7"
bright_cyan = "#ea9a97"
bright_white = "#e0def4"

[light.seed]
surface = "#faf4ed"
ink = "#575279"
accent = "#d7827e"
added = "#56949f"
removed = "#b4637a"
highlight = "#907aa9"

[light.syntax]
comment = "#9893a5"
keyword = "#286983"
string = "#ea9d34"
string_special = "#ea9d34"
escape = "#286983"
number = "#ea9d34"
boolean = "#d7827e"
type_name = "#56949f"
type_builtin = "#56949f"
constructor = "#56949f"
function = "#d7827e"
function_builtin = "#d7827e"
macro_name = "#907aa9"
property = "#56949f"
constant = "#ea9d34"
variable = "#575279"
variable_special = "#b4637a"
parameter = "#907aa9"
operator = "#797593"
punctuation = "#797593"
tag = "#56949f"
attribute = "#907aa9"
label = "#56949f"
invalid = "#b4637a"

[light.terminal.ansi]
black = "#f2e9e1"
red = "#b4637a"
green = "#286983"
yellow = "#ea9d34"
blue = "#56949f"
magenta = "#907aa9"
cyan = "#d7827e"
white = "#575279"
bright_black = "#9893a5"
bright_red = "#b4637a"
bright_green = "#286983"
bright_yellow = "#ea9d34"
bright_blue = "#56949f"
bright_magenta = "#907aa9"
bright_cyan = "#d7827e"
bright_white = "#575279"
